version: "3"

services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  node_modules:
  mysqldata:
